apiVersion: v1
kind: Service
metadata:
  name: locusthub-admin
spec:
  type: {{ .Values.adminService.type }}
  selector:
    app: locusthub-admin
  ports:
    - port: {{ .Values.adminService.port }}
      targetPort: 80

