{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secrets" .Release.Name) .Values.secret.name }}
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ .Values.secret.stringData.MYSQL_PASSWORD | quote }}
  ALIYUN_OSS_ACCESS_KEY_ID: {{ .Values.secret.stringData.ALIYUN_OSS_ACCESS_KEY_ID | quote }}
  ALIYUN_OSS_ACCESS_KEY_SECRET: {{ .Values.secret.stringData.ALIYUN_OSS_ACCESS_KEY_SECRET | quote }}
  DEMO_TOKEN: {{ .Values.secret.stringData.DEMO_TOKEN | quote }}
{{- end }}

